# Generated by Django 4.2 on 2024-07-17 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_title', models.CharField(max_length=100, verbose_name='Название привычки')),
                ('location', models.CharField(max_length=250, verbose_name='Место где выполняется привычка')),
                ('time_perform', models.DateTimeField(verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=300, verbose_name='Какие действия надо выполнить')),
                ('pleasant_habit', models.BooleanField(default=False, verbose_name='Это приятная привычка')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='статус публикации')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
